[package]
name = "tiled_render_experiment"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy" }
bevy_prototype_lyon = { git = "https://github.com/colepoirier/bevy_prototype_lyon", branch = "bevy-main" }
crossbeam-channel = "0.5.5"
futures-lite = "1.12.0"
vlsir = "1.0.0"
layout21 = { git = "https://github.com/colepoirier/Layout21" }
geo = "0.22.1"
csv = "1.1.6"
bitflags = "1.3.2"
itertools = "0.10.3"

[profile.dev.package.layout21]
opt-level = 3

[profile.dev.package."*"]
opt-level = 1

[profile.release]
debug = true
